baseURL = 'https://drmanpreetayurveda.com'
languageCode = 'en-us'
title = 'Dr Manpreet Singh'
theme = 'DoIt'


[params]
  # DoIt theme version
  version = "0.4.X"
  title = "Dr Manpreet Singh | Ayurveda"
  # site description
  description = "Dr Manpreet Singh"
  # site keywords
  keywords = ["ayurveda"]
  images = ["/manpreet_image.jpg"]
  optimizeImages = true
  enablePWA = false
  # [Experimental] cache remote images in markdown, more info: https://github.com/HEIGE-PCloud/DoIt/pull/860#issue-1574342372
  cacheRemoteImages = true
  # [Experimental] resize method for srcset attribute in optimizeImages, more info: https://gohugo.io/content-management/image-processing/#image-processing-options
  srcsetSmallResizeMethod = "700x webp Lanczos q75"
  srcsetDefaultResizeMethod = "1200x webp Lanczos q75"
  srcsetLargeResizeMethod = "2000x webp Lanczos q75"
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "DoIt"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
  [params.header]
    #  Theme change mode
    # theme change mode ("switch", "select")
    themeChangeMode = "select"
    #  Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/healthcare.png"
      # title name
      name = "Dr Manpreet Singh"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      #  whether to use typeit animation for title name
      typeit = false
  [params.footer]
    enable = true
    #  Custom content (HTML format is supported)
    custom = ''
    #  whether to show Hugo and theme info
    hugo = false
    #  Hosted on (HTML format is supported)
    # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreferrer">GitHub Pages</a>
    hostedOn = 'github'
    #  whether to show copyright info
    copyright = true
    #  whether to show the author
    author = true
    # Site creation time
    since = 2019
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.page]
    #  whether to hide a page from home page
    hiddenFromHomePage = false
    #  whether to hide a page from search results
    hiddenFromSearch = false
    #  whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    #  whether to enable the ruby extended syntax
    ruby = true
    #  whether to enable the fraction extended syntax
    fraction = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    #  configure the link to the source file of the post
    linkToSource = false
    # "https://github.com/user/repo/blob/main/{path}"
    #  configure the link to edit the post
    linkToEdit = false
    # "https://github.com/user/repo/edit/main/{path}"
    # "https://gitlab.com/user/repo/-/edit/main/{path}"
    # "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
    #  configure the link to report issue for the post
    linkToReport = false
    # "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
    #  whether to show the full text content in RSS
    rssFullText = false
    #  whether to enable series navigation
    seriesNavigation = true
    # whether to enable last modified time
    enableLastMod = false
    # whether to enable word count
    enableWordCount = false
    # whether to enable reading time estimation
    enableReadingTime = false
    [params.page.comment]
      enable = true
      # Disqus comment config
      [params.page.comment.disqus]
        # 
        enable = true
        # Disqus shortname to use Disqus in posts
        shortname = "Manpreet"

[params.author]
    name = "Manpreet Singh"
    email = "Manpreetsingh254.sm@gmail.com"
    link = ""
    avatar = "/manpreet_image.jpg"
    gravatarEmail = ""
[params.home]
    # DoIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      # Place your avatar file under static or assets directory
      # The filepath is relative to the static or assets directory
      avatarURL = "/manpreet_image.jpg"
      # URL the avatar links to
      avatarLinkURL = ""
      # DoIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "The Ayurveda Way to Health and Wellness"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # DoIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # DoIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = true
[params.social]
    Linkedin = ""
    Twitter = "xxxx"
    Instagram = "xxxx"
    Facebook = "xxxx"
    Telegram = "xxxx"
    Snapchat = ""
    Whatsapp = "+918264333880"
    Email = "xxxx@xxxx.com"

[params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = true

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false